### ISSUE TITLE
Dataset construction

### ISSUE THREAD

**Issue by yarqian** [liyucs/RAGNet#3]
Many thanks for your work. But I am confused about the dataset used in your codes. For 90 real-world training images from Berkeley real dataset, there are only the 'blended' and 'transmission_layer' images while for the synthetic dataset, the input is the trasmission and the reflection images. But in your 'prepare_data', the input is the transmission_layer, reflection_layer and blended images. So I am sorry to ask would you please give more details about the dataset construction. Many thanks.

**Comment by liyucs** [comment]
Thank you for your attention to our work!
For real data, we only use the blended/transmission layer; for synthetic data, we use blended/transmission/reflection layer.  As shown in line 247/257 in solver.py, we use different losses for these two scenarios. In fact, since the ground-truth reflection layer is unavailable, the corresponding loss terms are
excluded when training with real-world images.
